import * as THREE from 'three';
import {modelStates,visibleModels} from './model_parts.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {OrbitControls} from './vendor/OrbitControls.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let catalog,kind='fighter',selected,data,activeMove,animation,frame=0,playing=false,tab='moves',model,bones=[],rest=[],rig,overlays=new THREE.Group(),stageScene,modelParts,modelMeshes=[],currentModelSelection="base",busy=0,loadVersion=0;
const viewport=$('#viewport'),scene=new THREE.Scene();scene.background=new THREE.Color('#111923');scene.fog=new THREE.Fog('#111923',220,900);
const camera=new THREE.PerspectiveCamera(40,1,.1,3000);camera.position.set(45,22,60);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;viewport.append(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,12,0);controls.enableDamping=true;
scene.add(new THREE.HemisphereLight(0xe7f0ff,0x586a82,2.3));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(30,80,60);scene.add(light);
const grid=new THREE.GridHelper(600,60,0x3d4b5c,0x263341);scene.add(grid);scene.add(overlays);
new ResizeObserver(()=>{camera.aspect=viewport.clientWidth/viewport.clientHeight;camera.updateProjectionMatrix();renderer.setSize(viewport.clientWidth,viewport.clientHeight)}).observe(viewport);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function status(text,error=false){$('#status').textContent=text;$('#status').style.color=error?'#ffab8d':''}
async function api(path,body){return window.workshop.request(path,body)}
function task(fn){return async(...args)=>{try{busy++;await fn(...args)}catch(e){status(e.message,true);console.error(e)}finally{busy--}}}
async function refresh(){catalog=await api('/api/catalog');library()}
function library(){const list=kind==='stage'?catalog.stages:catalog.fighters.filter(f=>kind==='costume'?f.kind==='costume':f.kind!=='costume');const query=$('#search').value.toLowerCase();$('#count').textContent=list.length;$('#library-title').textContent=kind==='costume'?'Costume packs':kind==='fighter'?'Fighter library':'Custom stages';$('#library-list').innerHTML=list.filter(x=>x.name.toLowerCase().includes(query)).map(f=>`<div class="asset ${selected?.id===f.id?'selected':''}" data-id="${esc(f.id)}"><div class="avatar">${esc(f.prefix||'ST')}</div><div>${esc(f.name)}<small>${f.stock?'Original fighter':f.kind==='stage'?(f.enabled?'Compiled stage':'Stage draft'):f.kind==='costume'?'Additional costumes':'Custom character'}</small></div></div>`).join('');$$('.asset').forEach(e=>e.onclick=task(()=>select(e.dataset.id)))}
async function select(id){const current=++loadVersion;playing=false;animation=null;activeMove=null;$('#play').textContent='Play';selected=[...catalog.fighters,...catalog.stages].find(f=>f.id===id);kind=selected.kind;$$('[data-tab]').forEach(b=>b.hidden=kind==='costume'&&['lua','attributes','stage'].includes(b.dataset.tab));modelParts=null;$('#model-preview').value='auto';$('#model-preview-field').hidden=kind==='stage';$$('[data-kind]').forEach(b=>b.classList.toggle('active',b.dataset.kind===kind));frame=0;$('#timeline').value=0;$('#frame-label').textContent='0 / 0';for(const id of ['play','prev','next','timeline','speed','move-search','export-animations'])$('#'+id).disabled=kind==='stage';$('#move-search').value='';library();$('#asset-name').textContent=selected.name;$('#asset-type').textContent=kind==='costume'?'ADDITIONAL COSTUMES':kind==='fighter'?'CHARACTER DATA':'STAGE COMPOSER';$('#asset-badge').textContent=selected.stock?'Original':kind==='costume'?'Additive costume pack':'Custom package';$('#clone').disabled=kind!=='fighter';$('#costume').disabled=kind==='stage';$('#save').disabled=selected.stock||kind==='costume';$('#save').textContent=kind==='costume'?'Textures save on import':kind==='stage'?'Compile & add to stage select':'Save character changes';status('Loading '+selected.name+'...');
 if(kind!=='stage'){
  data=await api('/api/fighter?id='+id);if(current!==loadVersion)return;
  $('#asset-meta').textContent=`${data.moves.length} actions | ${Object.keys(data.attributes).length} attributes | ${selected.costumes.length} colors`;
  $('#costume').innerHTML=selected.costumes.map(c=>`<option value="${esc(c.file)}">${esc(c.name)} | ${esc(c.file)}</option>`).join('');moves();setTab(kind==='costume'?'textures':'moves');await loadModel('/api/model?id='+id+'&costume='+$('#costume').value,current);
  const idle=data.moves.find(m=>m.label==='Wait1'||m.label==='Wait')||data.moves.find(m=>m.animationSize>32);if(idle)await chooseMove(idle.id);
 }else{
  stageScene=await api('/api/stage?id='+id);if(current!==loadVersion)return;
  $('#asset-meta').textContent=`${stageScene.meshes.length} meshes | ${stageScene.metadata.platforms.length} platforms | Blender glTF`;
  $('#moves-list').innerHTML='<div class="empty">Stage layers</div>'+stageScene.meshes.map(m=>`<div class="move">${esc(m.name)}<span>${esc(m.role)}</span></div>`).join('');$('#costume').innerHTML='';setTab('stage');await loadModel('/mods/'+id+'/stage.glb?v='+Date.now(),current);showStageCollision();
 }
 status(selected.name+' loaded')
}
function dispose(root){root?.traverse(o=>{o.geometry?.dispose();for(const m of (Array.isArray(o.material)?o.material:[o.material])){m?.map?.dispose();m?.dispose()}})}
async function loadModel(url,version=loadVersion){const gltf=await new GLTFLoader().loadAsync(url);if(version!==loadVersion){dispose(gltf.scene);return}if(model){scene.remove(model);dispose(model)}if(rig){scene.remove(rig);rig.dispose()}model=gltf.scene;modelParts=gltf.asset.extras?.melee_character;modelMeshes=[];scene.add(model);bones=[];model.traverse(o=>{if(o.userData.melee_bone_id!==undefined)bones[o.userData.melee_bone_id]=o;if(o.isMesh){o.frustumCulled=false;modelMeshes.push(o)}});rest=bones.map(b=>({position:b.position.clone(),quaternion:b.quaternion.clone(),scale:b.scale.clone(),euler:new THREE.Euler().setFromQuaternion(b.quaternion,'ZYX')}));rig=new THREE.SkeletonHelper(model);rig.visible=$('#show-rig').checked;scene.add(rig);buildModelSelector();applyModelVisibility();frameModel();$('#viewport-status').textContent=kind!=='stage'?`${bones.length} joints | ${selected.costumes.find(c=>c.file===$('#costume').value)?.name||''}`:`${stageScene.meshes.reduce((n,m)=>n+m.indices.length/3,0).toLocaleString()} triangles`;if(animation)pose();if(tab==='submodels')details()}
function frameModel(front=false){if(!model)return;const box=new THREE.Box3();model.traverseVisible(o=>{if(o.isMesh)box.union(new THREE.Box3().setFromObject(o))});if(box.isEmpty())return;const size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());const radius=Math.max(size.x,size.y,size.z);controls.target.copy(center);camera.position.copy(center).add(kind!=='stage'?(front===true?new THREE.Vector3(0,radius*.04,radius*1.45):new THREE.Vector3(radius*.7,radius*.3,radius*1.45)):new THREE.Vector3(radius*.2,radius*.15,radius*1.1));camera.far=Math.max(3000,radius*10);camera.updateProjectionMatrix();controls.update()}
function moves(){const q=$('#move-search').value.toLowerCase();$('#moves-list').innerHTML=data.moves.filter(m=>m.label.toLowerCase().includes(q)).map(m=>`<div class="move ${activeMove?.id===m.id?'selected':''}" data-move="${m.id}">${esc(m.label)}<span>${String(m.id).padStart(3,'0')}</span></div>`).join('');$$('[data-move]').forEach(e=>e.onclick=task(()=>chooseMove(Number(e.dataset.move))))}
async function chooseMove(id){activeMove=data.moves[id];const requested=activeMove;animation=null;frame=0;playing=false;$('#play').textContent='Play';moves();details();applyModelVisibility();if(activeMove.animationSize>=32){const result=await api('/api/animation?id='+selected.id+'&action='+id);if(activeMove!==requested)return;animation=result;$('#timeline').max=animation.frames;pose();status(activeMove.label+' | '+animation.frames+' frames')}else status('This action has no separate animation');}
function sphere(position,radius,color,parent=overlays){const mesh=new THREE.Mesh(new THREE.SphereGeometry(Math.max(.05,radius),14,9),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.24,depthWrite:false}));mesh.position.copy(position);parent.add(mesh);return mesh}
function clearOverlays(){for(const o of [...overlays.children]){overlays.remove(o);dispose(o)}}
function pose(){if(!model)return;for(let i=0;i<bones.length;i++){const b=bones[i],r=rest[i];b.position.copy(r.position);b.scale.copy(r.scale);b.quaternion.copy(r.quaternion);if(animation?.nodes[i]){const e=r.euler.clone();for(const t of animation.nodes[i]){const value=t.values[Math.min(Math.floor(frame),t.values.length-1)];if(t.type>=1&&t.type<=3)e[['x','y','z'][t.type-1]]=value;if(t.type>=5&&t.type<=7)b.position[['x','y','z'][t.type-5]]=value;if(t.type>=8&&t.type<=10)b.scale[['x','y','z'][t.type-8]]=value}b.quaternion.setFromEuler(e)}}model.updateMatrixWorld(true);$('#timeline').value=frame;$('#frame-label').textContent=`${Math.floor(frame)} / ${animation?.frames||0}`;if(kind!=='stage'){applyModelVisibility();showBoxes()}}
function showBoxes(){clearOverlays();if($('#show-hurt').checked)for(const h of data.hurtboxes?.Hurtboxes||[]){const b=bones[h.BoneIndex];if(!b)continue;const a=new THREE.Vector3(h.X1,h.Y1,h.Z1).applyMatrix4(b.matrixWorld),c=new THREE.Vector3(h.X2,h.Y2,h.Z2).applyMatrix4(b.matrixWorld);sphere(a,h.Size,0x81c965);sphere(c,h.Size,0x81c965);const length=a.distanceTo(c);if(length>.01){const m=new THREE.Mesh(new THREE.CylinderGeometry(h.Size,h.Size,length,12),new THREE.MeshBasicMaterial({color:0x81c965,transparent:true,opacity:.18,depthWrite:false}));m.position.copy(a).lerp(c,.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),c.sub(a).normalize());overlays.add(m)}}
 if($('#show-hit').checked&&activeMove){const boxes=new Map();for(const e of activeMove.events){if(e.frame>frame)continue;const p=e.parameters;if(e.command==='CreateHitbox')boxes.set(p.ID,{...p});else if(e.command==='ClearHitboxes')boxes.clear();else if(e.command==='RemoveHitbox')boxes.delete(p.ID??p.HitboxID);else if(e.command==='AdjustHitboxDamage'&&boxes.has(p.HitboxID))boxes.get(p.HitboxID).Damage=p.Damage}for(const p of boxes.values()){const signed=v=>v>32767?v-65536:v;const point=new THREE.Vector3(signed(p.Z)*.003906,signed(p.Y)*.003906,signed(p.X)*.003906);const bone=bones[p.Bone];if(bone)point.applyMatrix4(bone.matrixWorld);sphere(point,p.Size/256,0xff5252)}}}
function showStageCollision(){clearOverlays();if(!stageScene)return;for(const p of stageScene.metadata.platforms){const geometry=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(...p.a,0),new THREE.Vector3(...p.b,0)]);overlays.add(new THREE.Line(geometry,new THREE.LineBasicMaterial({color:p.dropThrough?0x88ddff:0xa7e66b,depthTest:false})));}for(const s of stageScene.metadata.spawns)sphere(new THREE.Vector3(...s,0),2,0xe9bc65)}
function setTab(name){tab=name;$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));details()}
function details(){const panel=$('#detail-content');if(tab==='moves'){if(!activeMove){panel.innerHTML='<div class="empty">Select an action to inspect its events and damage data.</div>';return}const hit=activeMove.events.filter(e=>e.command==='CreateHitbox');panel.innerHTML=`<table><thead><tr><th>FRAME</th><th>HITBOX</th><th>DAMAGE</th><th>ANGLE</th><th>GROWTH</th><th>BASE KB</th><th>SIZE</th><th>BONE</th></tr></thead><tbody>${hit.map(e=>{let p=e.parameters;return `<tr><td>${e.frame}</td><td>${p.ID}</td><td>${p.Damage}%</td><td>${p.Angle} degrees</td><td>${p.KBG}</td><td>${p.BKB}</td><td>${(p.Size/256).toFixed(2)}</td><td>${p.Bone}</td></tr>`}).join('')}</tbody></table>${!hit.length?'<p class="empty">No CreateHitbox events in this action.</p>':''}<details class="data-section"><summary>Full movescript | ${activeMove.events.length} events</summary><textarea id="move-script" class="script-editor" ${selected.stock||kind==='costume'?'readonly':''}>${esc(activeMove.script)}</textarea>${selected.stock||kind==='costume'?'':'<button id="apply-script">Apply movescript</button>'}</details><p class="notice">Script events are shown in order. Conditional behavior and callbacks remain visible in All data.</p>`;
 if(!selected.stock&&kind!=='costume')$('#apply-script').onclick=task(async()=>{const script=$('#move-script').value;await api('/api/fighter/save',{id:selected.id,attributes:data.attributes,moves:[{id:activeMove.id,script}]});data=await api('/api/fighter?id='+selected.id);activeMove=data.moves[activeMove.id];details();showBoxes();status('Movescript compiled and saved to this character package')})}
 else if(tab==='lua'){task(()=>showLua(panel))()}
 else if(tab==='textures'){task(()=>showTextures(panel))()}
 else if(tab==='submodels'){showSubmodels(panel)}
 else if(tab==='attributes'){if(kind==='stage')return;panel.innerHTML='<table>'+Object.entries(data.attributes).map(([k,v])=>`<tr><td>${esc(k.replace(/([a-z])([A-Z])/g,'$1 $2'))}</td><td><input data-attr="${esc(k)}" type="${typeof v==='number'?'number':'text'}" step="any" value="${esc(v)}" ${selected.stock||kind==='costume'?'disabled':''}></td></tr>`).join('')+'</table>';$$('[data-attr]').forEach(e=>e.oninput=()=>{data.attributes[e.dataset.attr]=typeof data.attributes[e.dataset.attr]==='number'?Number(e.value):e.value;$('#save').disabled=false})}
 else if(tab==='sections'){if(kind==='stage')return;panel.innerHTML=Object.entries(data.sections).map(([k,v])=>`<details class="data-section"><summary>${esc(k)}</summary><pre>${esc(JSON.stringify(v,null,2))}</pre></details>`).join('')+`<details class="data-section"><summary>Complete DAT graph | ${data.graph.length} blocks</summary><p class="notice">Every data block and relocation is retained. Unknown values are not assigned speculative names.</p><input id="block-id" type="number" value="0" min="0" max="${data.graph.length-1}" aria-label="Raw data block"><pre id="block-raw"></pre></details>`;$('#block-id').oninput=()=>{const node=data.graph[Number($('#block-id').value)];if(node){const bytes=atob(node.bytes);$('#block-raw').textContent=JSON.stringify(node.references,null,2)+'\n\n'+[...bytes].map(c=>c.charCodeAt(0).toString(16).padStart(2,'0')).join(' ')}};$('#block-id').oninput()}
 else if(tab==='stage'){if(kind!=='stage'){panel.innerHTML='<div class="empty">Import a Blender GLB/glTF scene or choose a custom stage to edit platforms and boundaries.</div>';return}const m=stageScene.metadata;panel.innerHTML=`<div class="notice">X = horizontal, Y = up. Green lines are solid floors; blue lines allow dropping through. Meshes are visual geometry; collision is authored below.</div><div id="platforms">${m.platforms.map((p,i)=>`<div class="platform-row"><input class="pname" value="${esc(p.name||'Platform '+i)}" data-platform="${i}" data-key="name"><input type="number" step="any" value="${p.a[0]}" data-platform="${i}" data-key="a0" aria-label="Platform ${i} left X"><input type="number" step="any" value="${p.a[1]}" data-platform="${i}" data-key="a1" aria-label="Platform ${i} left Y"><span>to</span><input type="number" step="any" value="${p.b[0]}" data-platform="${i}" data-key="b0" aria-label="Platform ${i} right X"><input type="number" step="any" value="${p.b[1]}" data-platform="${i}" data-key="b1" aria-label="Platform ${i} right Y"><label><input type="checkbox" data-platform="${i}" data-key="dropThrough" ${p.dropThrough?'checked':''}> Drop</label><button data-remove-platform="${i}">Remove</button></div>`).join('')}</div><button id="add-platform">+ Platform</button><details class="data-section"><summary>Spawn points, camera, and blast boundaries</summary><textarea id="metadata-json" style="width:100%;height:180px;background:#10161e;color:#c9d7e5">${esc(JSON.stringify({spawns:m.spawns,cameraBounds:m.cameraBounds,blastBounds:m.blastBounds},null,2))}</textarea><button id="apply-bounds">Apply boundaries</button></details>`;$$('[data-platform]').forEach(e=>e.onchange=()=>{const p=m.platforms[e.dataset.platform],k=e.dataset.key;if(k==='name')p.name=e.value;else if(k==='dropThrough')p.dropThrough=e.checked;else p[k[0]][Number(k[1])]=Number(e.value);showStageCollision()});$$('[data-remove-platform]').forEach(e=>e.onclick=()=>{m.platforms.splice(Number(e.dataset.removePlatform),1);details();showStageCollision()});$('#add-platform').onclick=()=>{m.platforms.push({name:'Platform '+(m.platforms.length+1),a:[-25,30],b:[25,30],dropThrough:true});details();showStageCollision()};$('#apply-bounds').onclick=task(async()=>{Object.assign(m,JSON.parse($('#metadata-json').value));showStageCollision();status('Boundaries updated; compile to apply in game')})}}
$('#search').oninput=library;$('#move-search').oninput=()=>{if(kind!=='stage')moves()};$$('[data-kind]').forEach(b=>b.onclick=()=>{kind=b.dataset.kind;$$('[data-kind]').forEach(x=>x.classList.toggle('active',x===b));library()});$$('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('#costume').onchange=task(()=>loadModel('/api/model?id='+selected.id+'&costume='+$('#costume').value));$('#reset-view').onclick=frameModel;$('#front-view').onclick=()=>frameModel(true);$('#show-rig').onchange=()=>{if(rig)rig.visible=$('#show-rig').checked};$('#show-hit').onchange=$('#show-hurt').onchange=()=>{if(kind!=='stage'){applyModelVisibility();showBoxes()}};$('#play').onclick=()=>{playing=!playing;$('#play').textContent=playing?'Pause':'Play'};$('#timeline').oninput=()=>{frame=Number($('#timeline').value);pose()};$('#prev').onclick=()=>{frame=Math.max(0,Math.floor(frame)-1);pose()};$('#next').onclick=()=>{frame=Math.min(animation?.frames||0,Math.floor(frame)+1);pose()};$('#clone').onclick=()=>{$('#clone-name').value=selected.name==='Captain Falcon'?'Falcon Clone':selected.name+' Clone';$('#clone-dialog').showModal()};$('#confirm-clone').onclick=task(async e=>{e.preventDefault();$('#clone-dialog').close();status('Creating independent fighter package...');const f=await api('/api/clone',{base:selected.id,name:$('#clone-name').value});await refresh();await select(f.id);status('Clone created and registered for character select')});$('#save').onclick=task(async()=>{status('Building mod package...');if(kind==='fighter')await api('/api/fighter/save',{id:selected.id,attributes:data.attributes});else await api('/api/stage/save',{id:selected.id,metadata:stageScene.metadata});await refresh();status('Saved. The next mod-enabled game launch will load this package.')});$('#export').onclick=task(async()=>{status('Preparing Blender export...');const url=kind==='stage'?'/mods/'+selected.id+'/stage.glb':'/api/export?id='+selected.id+'&costume='+$('#costume').value+'&animations='+($('#export-animations').checked?'1':'0')+'&selection='+encodeURIComponent(currentModelSelection);const result=await window.workshop.exportAsset(url,selected.id+'.glb');status(result.canceled?'Export canceled':'Saved '+result.path)});
$('#blender').onclick=task(async()=>{const result=await window.workshop.exportAsset('/download/blender-addon.py','melee_workshop.py');status(result.canceled?'Export canceled':'Blender addon saved to '+result.path)});
$('#import-stage').onclick=task(async()=>{status('Choose a Blender stage...');const result=await window.workshop.importStage();if(result.canceled){status('Import canceled');return}await refresh();await select(result.id);status('Scene imported. Set collision and spawn points, then compile the stage.')});
window.workshop.onCommand(command=>{const ids={import:'import-stage',export:'export',blender:'blender',clone:'clone',save:'save'};if(ids[command])$('#'+ids[command]).click()});

function buildModelSelector(){
 const picker=$('#model-preview'),old=picker.value;
 picker.innerHTML='<option value="auto">Follow selected move</option><option value="base">Main model</option>';
 const variants=(modelParts?.groups||[]).flatMap(g=>g.variants.filter(v=>v.id!==g.default).map(v=>({g:g.id,...v})));
 if(variants.length)picker.innerHTML+='<optgroup label="Submodels">'+variants.map(v=>`<option value="part:${v.g}:${v.id}">${esc(v.label)}</option>`).join('')+'</optgroup>';
 picker.value=[...picker.options].some(o=>o.value===old)?old:'auto';
}
function applyModelVisibility(){
 if(kind==='stage'||!modelParts)return;
 const mode=$('#model-preview').value;
 const states=modelStates(modelParts,activeMove,frame);
 currentModelSelection=mode==='auto'?'states:'+states.join(','):mode;
 const active=visibleModels(modelParts,modelMeshes.map(o=>o.userData.melee_dobj),currentModelSelection);
 for(const mesh of modelMeshes)mesh.visible=active.has(mesh.userData.melee_dobj)&&!mesh.userData.melee_hidden;
 const visible=[...new Set(modelMeshes.filter(o=>o.visible).map(o=>o.userData.melee_dobj))];
 viewport.dataset.visibleDobjs=visible.join(',');viewport.dataset.modelSelection=currentModelSelection;
 let label=mode==='auto'?modelParts.groups.filter(g=>states[g.id]!==g.default).map(g=>g.variants.find(v=>v.id===states[g.id])?.label).filter(Boolean).join(', '):$('#model-preview').selectedOptions[0]?.textContent;
 if(!label)label='Main model';
 $('#model-status').textContent=label+' | '+visible.length+' visible parts';
}
function showSubmodels(panel){
 if(kind==='stage'||!modelParts){panel.innerHTML='<div class="empty">Choose a character to inspect its alternate models.</div>';return}
 const variants=modelParts.groups.flatMap(g=>g.variants.filter(v=>v.id!==g.default).map(v=>({group:g.id,...v})));
 panel.innerHTML='<p class="notice">Move-specific forms are kept separate from the main model. Select a form to inspect and export it. Follow selected move uses the movescript; callback-driven transitions may require choosing a form.</p>'+(modelParts.prefix==='Kb'?'<p class="notice">Stone randomly chooses one of five forms in game. The held-move preview uses Stone form 1.</p>':'')+variants.map(v=>`<div class="submodel-card"><div><strong>${esc(v.label)}</strong><small>${v.dobjs.length} model parts</small></div><button data-preview-part="part:${v.group}:${v.id}">Preview</button><div class="related-moves">${v.moves.slice(0,12).map(id=>`<button data-part-move="${id}">${esc(data.moves[id]?.label||'Action '+id)} (${id})</button>`).join('')}</div></div>`).join('')+(!variants.length?'<div class="empty">No alternate forms in this costume visibility table.</div>':'');
 $$('[data-preview-part]').forEach(button=>button.onclick=()=>{$('#model-preview').value=button.dataset.previewPart;applyModelVisibility();frameModel()});
 $$('[data-part-move]').forEach(button=>button.onclick=task(async()=>{$('#model-preview').value='auto';await chooseMove(Number(button.dataset.partMove));frameModel()}));
}
$('#model-preview').onchange=()=>{applyModelVisibility();frameModel()};

let last=performance.now();function tick(now){requestAnimationFrame(tick);const dt=Math.min(.1,(now-last)/1000);last=now;if(playing&&animation){frame=(frame+dt*60*Number($('#speed').value))%(animation.frames||1);pose()}controls.update();renderer.render(scene,camera)}requestAnimationFrame(tick);
await task(async()=>{await refresh();await select('stock-Ca')})();


async function showTextures(panel){
 if(kind==='stage'){panel.innerHTML='<div class="empty">Choose a character to inspect textures.</div>';return}
 const id=selected.id,costume=$('#costume').value;panel.innerHTML='<p>Reading costume textures...</p>';
 const list=await api('/api/textures?id='+id+'&costume='+costume);if(tab!=='textures'||selected.id!==id)return;
 const path=i=>'/api/texture?id='+id+'&costume='+costume+'&image='+i;
 panel.innerHTML='<p class="notice">Left: original Melee texture from your ISO. Right: this package. PNG imports must keep the original dimensions; GLB exports include the edited textures for Blender.</p><div class="icon-actions"><button data-import-icon="css" '+(selected.stock||kind==='costume'?'disabled':'')+'>Import CSS icon (64 x 56)</button> <button data-import-icon="stock" '+(selected.stock||kind==='costume'?'disabled':'')+'>Import stock icon (24 x 24)</button></div><div class="texture-grid">'+list.images.map(im=>`<div class="texture-card"><strong>Texture ${im.id} | ${im.width} x ${im.height}${im.changed?' | Edited':''}</strong><div class="texture-pair"><img loading="lazy" src="${path(im.id)}&original=1" alt="Original Melee texture ${im.id}"><img loading="lazy" src="${path(im.id)}" alt="Package texture ${im.id}"></div><button data-export-texture="${im.id}">Export PNG</button> <button data-import-texture="${im.id}" ${selected.stock?'disabled':''}>Import PNG</button></div>`).join('')+'</div>';
 $$('[data-export-texture]').forEach(b=>b.onclick=task(async()=>{const r=await window.workshop.exportAsset(path(b.dataset.exportTexture),'texture-'+b.dataset.exportTexture+'.png');status(r.canceled?'Export canceled':'Saved '+r.path)}));
 async function imported(options){const r=await window.workshop.importTexture({id,costume,...options});if(r.canceled){status('Import canceled');return}await loadModel('/api/model?id='+id+'&costume='+costume);await showTextures(panel);status('Texture saved. Reopen the game to load the updated package.')}
 $$('[data-import-texture]').forEach(b=>b.onclick=task(()=>imported({kind:'texture',image:Number(b.dataset.importTexture)})));
 $$('[data-import-icon]').forEach(b=>b.onclick=task(()=>imported({kind:b.dataset.importIcon})));
}

async function showLua(panel){
 if(kind!=='fighter'||selected.stock){panel.innerHTML='<p class="empty">Clone a fighter to add Lua behavior to its package.</p>';return}
 const id=selected.id;let doc=await api('/api/lua?id='+encodeURIComponent(id));if(tab!=='lua'||selected.id!==id)return;
 panel.innerHTML=`<div class="lua-toolbar"><strong>${esc(doc.language)}</strong><select id="lua-file" aria-label="Lua script">${doc.files.map(f=>`<option value="${esc(f)}">${esc(f)}</option>`).join('')}</select><button id="lua-new">New script</button><button id="lua-validate">Validate</button><button id="lua-save" class="primary">Save Lua</button><button id="lua-launch">Test in game</button></div><label><input type="checkbox" id="lua-entry" ${doc.file===doc.entry?'checked':''}> Use this file as fighter entry</label><textarea class="script-editor lua-editor" id="lua-source" spellcheck="false" aria-label="Lua source"></textarea><pre id="lua-diagnostic" role="status"></pre><p class="notice">Each player has an isolated Lua instance. Save before testing; the next game launch loads the saved script. Validation checks syntax. Runtime errors appear in the game log.</p><details id="lua-reference"><summary>Lua API reference</summary><pre class="lua-api-reference">${esc(doc.reference)}</pre></details>`;
 const source=$('#lua-source');source.value=doc.source;$('#lua-file').value=doc.file;
 source.onkeydown=e=>{if(e.key==='Tab'){e.preventDefault();source.setRangeText('    ',source.selectionStart,source.selectionEnd,'end')}};
 const request=()=>({id,file:$('#lua-file').value,source:source.value,entry:$('#lua-entry').checked});
 $('#lua-file').onchange=task(async()=>{doc=await api('/api/lua?id='+encodeURIComponent(id)+'&file='+encodeURIComponent($('#lua-file').value));source.value=doc.source;$('#lua-entry').checked=doc.file===doc.entry;$('#lua-diagnostic').textContent=''});
 $('#lua-new').onclick=()=>{const name=prompt('Script name (letters, numbers, underscores):','moves');if(!name)return;if(!/^[A-Za-z0-9_-]+$/.test(name)){status('Use letters, numbers, underscores or hyphens.',true);return}const file='scripts/'+name+'.lua';if(![...$('#lua-file').options].some(o=>o.value===file))$('#lua-file').add(new Option(file,file));$('#lua-file').value=file;source.value='local module = {}\n\nreturn module\n';$('#lua-entry').checked=false};
 $('#lua-validate').onclick=task(async()=>{const r=await api('/api/lua/validate',request());$('#lua-diagnostic').textContent=r.diagnostic;status(r.valid?'Lua syntax is valid':r.diagnostic,!r.valid)});
 $('#lua-save').onclick=task(async()=>{const r=await api('/api/lua/save',request());$('#lua-diagnostic').textContent=r.diagnostic;status('Saved '+r.file)});
 $('#lua-launch').onclick=task(async()=>{await api('/api/lua/save',request());const r=await api('/api/lua/launch',{});status(r.message)});
}


let communityRows=[],publishPackages=[],preparedUpload=null,communityTransfer=false,publisherConfigured=false;
function communityMessage(text,error=false){$('#community-message').textContent=text;$('#community-message').classList.toggle('error',error)}
function byteSize(n){return n>=1048576?(n/1048576).toFixed(1)+' MiB':Math.ceil(n/1024)+' KiB'}
function communityTab(publish){$('#community-browse').hidden=publish;$('#community-publish').hidden=!publish;$('#community-browse-tab').classList.toggle('active',!publish);$('#community-publish-tab').classList.toggle('active',publish)}
async function communityLoad(){
 communityMessage('Loading costume packs...');
 try{const doc=await api('/api/community/catalog?q='+encodeURIComponent($('#community-search').value));communityRows=doc.mods;publisherConfigured=doc.publisherConfigured;renderCommunity();communityMessage(communityRows.length?'Choose a pack to view its additional colors.':'No matching costume packs.');}
 catch(e){$('#community-mods').innerHTML='<div class="empty">The community repository is unavailable.</div>';communityMessage(e.message,true)}
}
function renderCommunity(){
 $('#community-count').textContent=communityRows.length+' costume '+(communityRows.length===1?'pack':'packs');
 $('#community-mods').innerHTML=communityRows.map(m=>`<article class="community-card"><div class="community-card-title"><h3>${esc(m.name)}</h3><span class="pill">${esc(m.version)}</span></div><p class="community-muted">${esc(catalog.fighters.find(f=>f.id===m.base)?.name||m.base)} | ${m.costumeCount} additional ${m.costumeCount===1?'color':'colors'} | ${byteSize(m.size)}</p><p>${esc(m.description||'Additional costumes that preserve the original color choices.')}</p><ul>${(m.costumes||[]).map(c=>`<li>${esc(c.name)}</li>`).join('')}</ul>${m.author?`<p class="community-muted">By ${esc(m.author)}</p>`:''}<button data-install-mod="${m.sha256}" class="${m.installed?'':'primary'}" ${communityTransfer?'disabled':''}>${m.installed?(m.enabled?'Disable pack':'Enable pack'):'Download & add costumes'}</button></article>`).join('');
 $$('[data-install-mod]').forEach(button=>button.onclick=task(async()=>{const m=communityRows.find(row=>row.sha256===button.dataset.installMod);if(m.installed){await api('/api/package/enabled',{id:m.installedId||m.id,enabled:!m.enabled});await communityLoad();await refresh();communityMessage(m.enabled?'Pack disabled. Reopen Melee to update its colors.':'Pack enabled. Reopen Melee to load its colors.');return}await transfer('install',{sha256:m.sha256});await refresh();await communityLoad();communityMessage('Costumes added. Reopen Melee to load the new colors.')}));
}
async function transfer(operation,payload){
 if(communityTransfer)throw new Error('A transfer is already in progress');
 communityTransfer=true;$('#community-transfer').hidden=false;$('#community-upload').disabled=true;renderCommunity();
 try{let job=await api('/api/community/'+operation,payload);for(;;){$('#community-transfer-label').textContent=job.phase+(job.totalBytes?' | '+byteSize(job.completedBytes)+' / '+byteSize(job.totalBytes):'');const progress=$('#community-progress');if(job.totalBytes&&job.completedBytes)progress.value=100*job.completedBytes/job.totalBytes;else progress.removeAttribute('value');if(job.status==='failed')throw new Error(job.error);if(job.status==='complete'){progress.value=100;return job.result}await new Promise(resolve=>setTimeout(resolve,300));job=await api('/api/community/job?id='+job.id)}}
 catch(e){communityMessage(e.message,true);throw e}
 finally{communityTransfer=false;renderCommunity();$('#community-upload').disabled=!preparedUpload||!publisherConfigured;}
}
async function publishLoad(){
 const doc=await api('/api/community/packages');publishPackages=doc.packages;publisherConfigured=doc.publisherConfigured;$('#community-package').innerHTML=publishPackages.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} (${p.costumes.length} colors)</option>`).join('');$('#community-prepare').disabled=!publishPackages.length;$('#community-publisher-state').textContent=publisherConfigured?'Publisher access is configured for this Workshop.':'Publisher access is not configured for this Workshop installation.';publishSelection();if(!publishPackages.length)communityMessage('Create a costume pack in Workshop before publishing.');
}
function publishSelection(){
 preparedUpload=null;$('#community-review').hidden=true;$('#community-upload').disabled=true;const p=publishPackages.find(p=>p.id===$('#community-package').value);$('#community-version').value=p?.version||'1.0.0';$('#community-author').value=p?.author||'';$('#community-description').value=p?.description||'';
}
$('#community-open').onclick=task(async()=>{$('#community-dialog').showModal();communityTab(false);await communityLoad()});
$('#community-close').onclick=()=>$('#community-dialog').close();
$('#community-browse-tab').onclick=()=>communityTab(false);
$('#community-publish-tab').onclick=task(async()=>{communityTab(true);await publishLoad()});
$('#community-refresh').onclick=task(communityLoad);
$('#community-search').onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();task(communityLoad)()}};
$('#community-package').onchange=publishSelection;
for(const selector of ['#community-version','#community-author','#community-description'])$(selector).oninput=()=>{preparedUpload=null;$('#community-upload').disabled=true;$('#community-review').hidden=true};
$('#community-prepare').onclick=task(async()=>{
 communityMessage('Preparing the selected costume files...');const review=await api('/api/community/prepare',{id:$('#community-package').value,version:$('#community-version').value,author:$('#community-author').value,description:$('#community-description').value});preparedUpload=review;const m=review.manifest;$('#community-review').hidden=false;$('#community-review').innerHTML=`<h3>Review upload</h3><strong>${esc(m.name)} | ${esc(m.version)}</strong><p>${m.costumes.length} additional colors | ${byteSize(review.size)}</p><p>${esc(m.description||'No description')}</p><ul>${m.costumes.map(c=>`<li>${esc(c.name)}</li>`).join('')}</ul><details><summary>${review.files.length} included files</summary><ul>${review.files.map(f=>`<li>${esc(f.path)} | ${byteSize(f.size)}</li>`).join('')}</ul></details>`;$('#community-upload').disabled=!publisherConfigured||communityTransfer;communityMessage('Review the pack, then choose Upload reviewed pack to publish it.');$('#community-upload').scrollIntoView({block:'nearest'});
});
$('#community-upload').onclick=task(async()=>{if(!preparedUpload)return;await transfer('upload',{preparedId:preparedUpload.preparedId});communityMessage('Pack published. It is now available in Mod Browser.');preparedUpload=null;$('#community-upload').disabled=true;});
function costumeColors(){const base=catalog.fighters.find(f=>f.id===$('#costume-pack-base').value);$('#costume-pack-colors').innerHTML=base.costumes.map((c,i)=>`<label><input type="checkbox" value="${esc(c.file)}" ${i===0?'checked':''}> ${esc(c.name)}</label>`).join('')}
$('#costume-create').onclick=()=>{$('#costume-pack-base').innerHTML=catalog.fighters.filter(f=>f.stock).map(f=>`<option value="${esc(f.id)}">${esc(f.name)}</option>`).join('');const base=selected?.stock?selected.id:selected?.base;$('#costume-pack-base').value=catalog.fighters.some(f=>f.stock&&f.id===base)?base:'stock-Lk';$('#costume-pack-name').value=(catalog.fighters.find(f=>f.id===$('#costume-pack-base').value)?.name||'New')+' Costume Pack';costumeColors();$('#costume-dialog').showModal()};
$('#costume-pack-base').onchange=costumeColors;
$('#costume-pack-confirm').onclick=task(async event=>{event.preventDefault();const choices=$$('#costume-pack-colors input:checked').map(c=>c.value);if(!choices.length)throw new Error('Choose at least one original color');status('Creating additional costume slots...');const m=await api('/api/costume/clone',{base:$('#costume-pack-base').value,name:$('#costume-pack-name').value,costumes:choices});$('#costume-dialog').close();await refresh();await select(m.id);status('Costume pack created. Import textures to customize its additional colors.');});
