"""Build simple front-facing option icons as native GX RGBA8 textures.

The flat grey fill and pale contour follow Melee's original menu illustrations
(MnMaAll.usd, MenMainConTop_Top: Screen Display and controller preview art).
SVG is the editable source; both icons use the same canvas and screen height.
The illuminated screen opening is exactly 4:3 or 16:9, respectively.
"""
from pathlib import Path
import json
import shutil
import subprocess
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets/ui/options"
INC = ROOT / "native/host/gxrt/monitor_native.inc"
WIDTH, HEIGHT = 128, 96


def rgba8(image):
    """GameCube RGBA8 stores AR and GB planes in each 4x4 tile."""
    pixels = image.load()
    out = bytearray()
    for by in range(0, image.height, 4):
        for bx in range(0, image.width, 4):
            tile = [pixels[bx+x, by+y] for y in range(4) for x in range(4)]
            out.extend(v for r, g, b, a in tile for v in (a, r))
            out.extend(v for r, g, b, a in tile for v in (g, b))
    return out


def main():
    resvg = shutil.which("resvg")
    if not resvg:
        raise SystemExit("resvg is required to rasterize the editable SVG icons")
    OUT.mkdir(parents=True, exist_ok=True)
    lines = ["/* Generated by tools/build_native_monitor_art.py. */",
             f"#define MONITOR_NATIVE_W {WIDTH}",
             f"#define MONITOR_NATIVE_H {HEIGHT}"]
    manifest = {"canvas": [WIDTH, HEIGHT], "pixel_format": "GX_TF_RGBA8",
                "reference": "MnMaAll.usd original menu preview illustrations: flat grey fill, pale contour, front-facing symbols.",
                "screen_height": 108, "icons": {}}
    for key, screen_width in (("narrow", 144), ("wide", 192)):
        x = (256-screen_width)//2
        svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 256 192">
  <g stroke="#EFEFEF" stroke-width="2" stroke-linejoin="round">
    <path d="M116 142V164H100L91 174H165L156 164H140V142Z" fill="#5B5D62"/>
    <rect x="{x-9}" y="16" width="{screen_width+18}" height="128" rx="5" fill="#5B5D62"/>
    <rect x="{x}" y="25" width="{screen_width}" height="108" rx="1" fill="#292D3B"/>
  </g>
  <path d="M{x+screen_width-7} 138H{x+screen_width-2}" stroke="#EFEFEF" stroke-width="2"/>
</svg>
'''
        source = OUT / f"monitor-{key}-native.svg"
        png = source.with_suffix(".png")
        source.write_text(svg, encoding="utf-8", newline="\n")
        subprocess.run([resvg, str(source), str(png)], check=True, capture_output=True)
        image = Image.open(png).convert("RGBA")
        data = rgba8(image)
        lines.append(f"static const unsigned char monitor_{key}_native_rgba8[] = {{")
        lines.extend(",".join(str(v) for v in data[i:i+40])+"," for i in range(0,len(data),40))
        lines.append("};")
        manifest["icons"][key] = {"source": source.name, "png": png.name,
            "screen_opening": [x,25,screen_width,108], "ratio": screen_width/108}
    INC.write_text("\n".join(lines)+"\n", newline="\n")
    (OUT/"monitor-native.json").write_text(json.dumps(manifest,indent=2)+"\n",newline="\n")
    print("Built native monitor RGBA8 textures and editable SVG sources")


if __name__ == "__main__":
    main()
