"""Pack the generated Options illustration into Melee's native I4 format.

The native menu owns the hover mesh, layered panel, material, camera and
animation. This replaces only its former Screen Display illustration.
"""
from pathlib import Path
import hashlib
import json
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/ui/options/controller-hover-generated.png"
OUTPUT = ROOT / "native/host/gxrt/controller_hover.inc"

def main():
    source = Image.open(SOURCE).convert("RGBA")
    bounds = source.getchannel("A").getbbox()
    if not bounds or source.getchannel("A").getextrema()[0] != 0:
        raise ValueError("A transparent generated illustration is required")
    image = ImageOps.contain(source.crop(bounds), (116, 88), Image.Resampling.LANCZOS)
    canvas = Image.new("RGBA", (128, 104))
    canvas.alpha_composite(image, ((128-image.width)//2, (104-image.height)//2))
    # I4 intensity also supplies alpha. Premultiply to retain the generated cutout.
    values = [((r*299 + g*587 + b*114)//1000)*a//255 for r,g,b,a in canvas.getdata()]
    data = bytearray(128*104//2)
    for y in range(104):
        for x in range(128):
            at = ((y//8)*16+x//8)*32+(y%8)*4+(x%8)//2
            data[at] |= (values[y*128+x]>>4) << (4 if x%2==0 else 0)
    lines = ["/* Generated by tools/build_controller_hover_art.py from generated UI artwork. */",
             "static const unsigned char controller_hover_i4[] = {"]
    lines += [",".join(str(v) for v in data[i:i+40])+"," for i in range(0,len(data),40)]
    OUTPUT.write_text("\n".join(lines)+"\n};\n", encoding="ascii", newline="\n")
    out = ROOT / "build/art/controller-hover";out.mkdir(parents=True, exist_ok=True)
    canvas.save(out/"native-source.png")
    (out/"manifest.json").write_text(json.dumps({"source":str(SOURCE.relative_to(ROOT)),
        "sourceSHA256":hashlib.sha256(SOURCE.read_bytes()).hexdigest(),"format":"GX_TF_I4",
        "size":[128,104],"nativeTarget":"MenMainConTop_Top_matanim_joint, joint40, image6",
        "nativePanelAndAnimationPreserved":True},indent=2)+"\n")
    print("Packed controller illustration; native panel and animation retained")

if __name__ == "__main__":main()
