"""Pack approved monitor artwork into the renderer; originals stay untouched."""
from pathlib import Path
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
lines=['/* Generated by tools/pack_monitor_art.py; source PNGs live in assets/ui/options. */']
for key, filename, correction in [('narrow','monitor-4x3-flat-v1.png',(4/3)/1.373),('wide','monitor-16x9-flat-v1.png',(16/9)/2.029)]:
    image=Image.open(ROOT/'assets/ui/options'/filename).convert('RGBA')
    box=image.getchannel('A').point(lambda a:255 if a>=32 else 0).getbbox()
    if not box: raise ValueError('Empty monitor artwork: '+filename)
    image=image.crop(box)
    aspect=image.width/image.height*correction
    height=192; width=round(height*aspect)
    image=image.resize((width,height),Image.Resampling.LANCZOS)
    pixels=image.tobytes()
    lines.append(f'static const int monitor_{key}_w = {width}, monitor_{key}_h = {height};')
    lines.append(f'static const unsigned char monitor_{key}_rgba[] = {{')
    lines += [','.join(str(v) for v in pixels[i:i+40])+',' for i in range(0,len(pixels),40)]
    lines.append('};')
(ROOT/'native/host/aurora_shim/monitor_art.inc').write_text('\n'.join(lines)+'\n',newline='\n')
