"""Embed the netplay UI art as compact, self-contained PNG textures.

Run ``python tools/pack_netplay_art.py`` after editing the source PNGs.  The
generated include exposes ``netplay_art::Image`` records for Aurora's existing
``aurora::gfx::png::parse_png_bytes({image.data, image.size})`` decoder.  Original
files are never modified.  Pillow is the only build-time dependency.
"""

from __future__ import annotations

import argparse
import hashlib
from io import BytesIO
import json
from pathlib import Path

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parents[1]
GLYPHS = ("a", "b", "x", "y", "start-pause")


def source_image(path: Path, *, transparent: bool) -> Image.Image:
    with Image.open(path) as source:
        image = source.convert("RGBA")
    alpha = image.getchannel("A")
    low, high = alpha.getextrema()
    if transparent and (low == 255 or high == 0):
        raise ValueError(f"Expected visible artwork with a transparent background: {path}")
    if not transparent and low != 255:
        raise ValueError(f"Expected opaque artwork: {path}")
    return image


def chrome_canvas(path: Path) -> Image.Image:
    image = source_image(path, transparent=True)
    bounds = image.getchannel("A").point(lambda a: 255 if a >= 32 else 0).getbbox()
    if bounds is None:
        raise ValueError(f"No visible chrome artwork: {path}")
    # Normalize the generated foreground only; the original menu draws the background.
    frame = image.crop(bounds).resize((734, 488), Image.Resampling.LANCZOS)
    canvas = Image.new("RGBA", (800, 600))
    canvas.alpha_composite(frame, (33, 54))
    return canvas


def controller_canvas(path: Path) -> Image.Image:
    image = source_image(path, transparent=True)
    bounds = image.getchannel("A").point(lambda a: 255 if a >= 8 else 0).getbbox()
    if bounds is None:
        raise ValueError(f"No visible controller artwork: {path}")
    illustration = ImageOps.contain(image.crop(bounds), (304, 224), Image.Resampling.LANCZOS)
    canvas = Image.new("RGBA", (320, 240))
    canvas.alpha_composite(illustration, ((320 - illustration.width) // 2,
                                        (240 - illustration.height) // 2))
    return canvas


def glyph_canvas(path: Path) -> Image.Image:
    # Preserve the shared canvas so A/B sizes and X/Y orientation stay accurate.
    image = source_image(path, transparent=True)
    if image.width != image.height:
        raise ValueError(f"GameCube glyphs require a square common canvas: {path}")
    return image.resize((128, 128), Image.Resampling.LANCZOS)


def encode_png(image: Image.Image) -> bytes:
    buffer = BytesIO()
    image.save(buffer, format="PNG", optimize=True, compress_level=9)
    data = buffer.getvalue()
    # Decode the exact exported PNG to verify dimensions and all RGBA values.
    with Image.open(BytesIO(data)) as decoded:
        if decoded.size != image.size or decoded.convert("RGBA").tobytes() != image.tobytes():
            raise ValueError("Packed PNG verification failed")
    return data


def pack(art_dir: Path, glyph_dir: Path, output: Path, packed_dir: Path) -> dict:
    assets = [
        ("controller", art_dir / "controller.png", controller_canvas, {}),
    ]
    assets += [("glyph_" + glyph.replace("-", "_"), glyph_dir / (glyph + ".png"),
                glyph_canvas, {}) for glyph in GLYPHS]
    prepared = []
    for name, path, transform, options in assets:
        image = transform(path, **options)
        data = encode_png(image)
        prepared.append((name, path, image, data))

    lines = [
        "/* Generated by tools/pack_netplay_art.py; edit source PNGs, not this file. */",
        "/* Decode with aurora::gfx::png::parse_png_bytes({image.data, image.size}). */",
        "namespace netplay_art {",
        "struct Image { const unsigned char* data; unsigned size, width, height; };",
    ]
    report = {"format": "RGBA8 PNG", "assets": []}
    for name, path, image, data in prepared:
        lines.append(f"static const unsigned char {name}_png[] = {{")
        lines += [",".join(f"0x{value:02x}" for value in data[start:start + 24]) + ","
                  for start in range(0, len(data), 24)]
        lines.append("};")
        lines.append(f"static const Image {name} = {{ {name}_png, sizeof({name}_png), "
                     f"{image.width}, {image.height} }};")
        try:
            source = str(path.resolve().relative_to(ROOT)).replace("\\", "/")
        except ValueError:
            source = str(path.resolve())
        report["assets"].append({
            "name": name, "source": source,
            "source_sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            "width": image.width, "height": image.height,
            "alpha_range": list(image.getchannel("A").getextrema()),
            "png_bytes": len(data), "rgba_bytes": image.width * image.height * 4,
            "packed_sha256": hashlib.sha256(data).hexdigest(),
        })
    lines.append("} // namespace netplay_art")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="ascii", newline="\n")
    packed_dir.mkdir(parents=True, exist_ok=True)
    for name, _path, _image, data in prepared:
        (packed_dir / (name + ".png")).write_bytes(data)
    report["total_png_bytes"] = sum(asset["png_bytes"] for asset in report["assets"])
    report["total_rgba_bytes"] = sum(asset["rgba_bytes"] for asset in report["assets"])
    (packed_dir / "manifest.json").write_text(json.dumps(report, indent=2) + "\n",
                                              encoding="utf-8", newline="\n")
    return report


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--art-dir", type=Path, default=ROOT / "assets/ui/gamecube-original")
    parser.add_argument("--glyph-dir", type=Path, default=ROOT / "assets/ui/gamecube-original")
    parser.add_argument("--output", type=Path,
                        default=ROOT / "native/host/aurora_shim/netplay_art.inc")
    parser.add_argument("--packed-dir", type=Path, default=ROOT / "build/art/netplay")
    args = parser.parse_args()
    report = pack(args.art_dir, args.glyph_dir, args.output, args.packed_dir)
    print(f"Packed {len(report['assets'])} RGBA textures into {args.output}")
    print(f"Embedded PNG: {report['total_png_bytes']:,} bytes; "
          f"decoded RGBA: {report['total_rgba_bytes']:,} bytes")
    print(f"Packed PNG previews and validation manifest: {args.packed_dir}")


if __name__ == "__main__":
    main()
